### ISSUE TITLE
Certain spawngroups go crazy sometimes

### ISSUE THREAD

**Issue by skerit** [vlad2305m/fabric-per-player-spawns#10]
Now and again I have an issue on my server where we suddenly get tons and tons of squids & dolphins spawning.
We're talking thousands.

I thought I knew exactly how to duplicate the issue, but my latest attempts have failed. Here's what it looks like:

![afbeelding](https://user-images.githubusercontent.com/755212/132999641-625c7054-183c-4ed0-96e1-f243770ef7f9.png)

Even though Carpet's `/spawn mobcaps` command says the mobcap for water_creatures is currently set at 66, over 1685 have actually spawned.

At first I thought it was some strange issue regarding spawn chunks (because this is just around spawn), but there's just a lot of water around my spawn, so that's probably a coincidence.

And it doesn't only happen here, something similar happens in the nether:

![afbeelding](https://user-images.githubusercontent.com/755212/132999728-141d6d9a-5e20-4615-9b81-6e3348aa8d49.png)

**Comment by vlad2305m** [comment]
Nice. Who set the mobcap to 66? And did you do anything to striders? How were you thinking this happens? Did you modify mobcaps and with what? What is your server's mod list?

**Comment by Apricityx** [comment]
same as him.
This is my mod list:
carpet-extra
carpet-tis-addition
fabric-api-0.37.2+1.17
fabric-carpet-1.17.1-1.4.45+v210811
graves-1.0.8+1.17.1.jar
krypton-0.1.4.jar
lithium
minimotd-fabric-mc1.17.1-2.0.4
Geyser-Fabric-1.4.3-SNAPSHOT
Dynmap-3.2.1-fabric-1.17.1

**Comment by vlad2305m** [comment]
Use proper mobcap modifier to set the mobcaps. Carpet is incompatible.

**Comment by vlad2305m** [comment]
Disabled for animals
