### ISSUE TITLE
1.18

### ISSUE THREAD

**Issue by EysseW** [vlad2305m/fabric-per-player-spawns#11]
Any plans for a 1.18 version? I would love to use this on my SMP with friends.

**Comment by vlad2305m** [comment]
Is it not in 1.18 as a vanilla feature now?

**Comment by EysseW** [comment]
You could be right, I haven't heard about it being so, but if you did, that probably so

**Comment by wulan17** [comment]
I didn't found anything about this on 1.18 changelogs
And i found this patch on paper repository
https://github.com/PaperMC/Paper/blob/master/patches/server/0367-implement-optional-per-player-mob-spawns.patch
Isn't this patch which this mod use?

**Comment by Apricityx** [comment]
I have tested it on 1.18.1.When the number of players increases, mobcaps also increases. But it is still not evenly distributed. I still need to rely on your mod, so please update it to 1.18.1!

**Comment by vlad2305m** [comment]
I literally tried to upgrade it to 1.18.1, but found code that already does the same thing with more stability, @Apricityx. You might want to just turn off the global cap to achieve the same effect.

**Comment by Apricityx** [comment]
> turn off the global cap
how to do this,I never heared about it before

**Comment by vlad2305m** [comment]
Guess I'll have to write a mod for that or add it to PMM

**Comment by Apricityx** [comment]
This mod is necessary for us.
Any way,thank you,that's what we needed.

**Comment by TechPro424** [comment]
Update to 1.19 please
