### ISSUE TITLE
Solo Mob Spawning Different From Vanilla

### ISSUE THREAD

**Issue by xDraxxis** [vlad2305m/fabric-per-player-spawns#2]
A player on my server was sitting AFK at a gold farm. He reported roughly 30 pigmen spawned prior to disabling the mod. Many more spawned after disabling. He was the only one on at the time. He was also able to compare it between our two servers, survival and creative. Creative didn't have the mod and was much faster as well. Is this what the mod is supposed to do?

**Comment by robert-sokol** [comment]
Can confirm as well, major difference in spawn cap after switching from paper to fabric with this mod. Tested with and without mod - with mod  enabled gold farm maxes out at 10 pigmen, vanilla rates without(ofc, without any other players online in nether).

**Comment by vlad2305m** [comment]
As said, there is some dodgy logic happening, especially if spawning space is small. For me it worked at insta-teleport nether->overworld gold farm just like vanilla, so the issue is when the mobs are already there. Perhaps just use https://www.curseforge.com/minecraft/mc-mods/proper-mobcap-modifier-fabric

**Comment by xDraxxis** [comment]
Does that replicate the features of this mod at all? From a brief look it seems like its a completely different thing.

**Comment by vlad2305m** [comment]
No. This mod is unique for making mobcaps properly multiplayer. That mod is unique for being compatible with this mod. 
A quick fix would be to check the amount of players > 1 before modifying mob spawns. Expect it tomorrow.

**Comment by xDraxxis** [comment]
Server crashes on player connection with latest build. https://gist.github.com/xDraxxis/71796593dc0d79c9ef222557425aef91

**Comment by vlad2305m** [comment]
@xDraxxis thank you, sorry for such a delay. Hope 1.0.2 works fine (tested with carpet for 0-2 players). Do you happen to know how to get carpet into dev environment?

**Comment by vlad2305m** [comment]
@xDraxxis There is a bug in vanilla that spectator players contribute to the mob cap. Are you sure there were no spectators when the player you were talking about AFKed on the farm? This is the only reasonable cause of mob cap difference I can think of other than using an incompatible mod for modifying mobcaps.

**Comment by xDraxxis** [comment]
The initial report of mop cap difference was sent to me when it was just a singular person online. I also don't know how to get into the carpet dev environment.

**Comment by vlad2305m** [comment]
New release fixes persistent counting bug. Please check it.

**Comment by xDraxxis** [comment]
I'll give it a try soon.  Haven't been playing a whole lot of Minecraft lately.

**Comment by vlad2305m** [comment]
@xDraxxis I just encountered a veeeery weird bug with Zaack (Issue "End/Nether"), so there probably will be another release ;)

**Comment by vlad2305m** [comment]
Can you encounter this with v2.0.0?

**Comment by xDraxxis** [comment]
Sorry to re-start this issue, but we're seeing differing spawn rates for hoglins and zombified piglins. Seems to be a similar issue to what I was encountering here.
