### ISSUE TITLE
Incompatibility with DimensionalThreading

### ISSUE THREAD

**Issue by JumperCzech** [vlad2305m/fabric-per-player-spawns#3]
WARNING: oi m8 wrong thread

**Comment by vlad2305m** [comment]
> WARNING: oi m8 wrong thread

It is an intentional thing, idk why, so I guess I will just remove it in a release here. Or make another mod to bridge this check with threads from DT if this is actually something important...

**Comment by vlad2305m** [comment]
Should be fine with 1.0.3
@JumperCzech Please test and report if there are any problems with this release (if you intended to)
