### ISSUE TITLE
Weird End/Nether issues

### ISSUE THREAD

**Issue by ZaackGoat** [vlad2305m/fabric-per-player-spawns#4]
Hello ! Sometimes no enderman or pigmen spawn in the end/nether anymore.
One time it happenned, there was tons of enderman on a side of the main island, and even tho I killed them all, none were spawning except in those 20 blos radius

Thanks for the mod ! Realy helpfull anyways !

**Comment by vlad2305m** [comment]
I also had that issue once, but reentering the nether fixed it and I couldn't reproduce it anymore. I thought it has something to do with exactly 0 mobs and I thought I already fixed it in the code. Do you have any ideas what can be causing it? Or can you describe that situation in terms of how many mobs and players were on the server and in which dimensions chronologically?

**Comment by ZaackGoat** [comment]
No clue to be honest, also I couldn't install the proper mobcap, server wouldn't launch with it and I don't know why.
I have phosphor, lithium & proximity chat as other mods that's all

**Comment by vlad2305m** [comment]
@ZaackGoat Thank you for providing mod list. I will test the pmm issue as soon as I have time, or, alternatively, you can send me the crash log from that time - the issue should be clear from there. (Or, maybe, you forgot to download "autoconfig updated api")

**Comment by ZaackGoat** [comment]
I switched to fabric again to try it, and yea was my bad for the autoconfig, might've missed it last time. For the moment everything works great, will let you know if I manage to re create the bug, thanks for the support !

**Comment by ZaackGoat** [comment]
For the moment everything seems fine, except in the nether, if there is someone in the nether, gold farms etc won't work, doesn't seem like it's a mobcap per player there

**Comment by ZaackGoat** [comment]
The bug reappeared in the end, no enderman can spawn on the main island or another enderman farm, they only spawn on one enderman farm on the side of the island, there are two farms and they only appear on one

**Comment by ZaackGoat** [comment]
Tried to light up the farm where they can spawn, they don't spawn anywhere when I do that, there is 0 enderman when I try a kill entity enderman

**Comment by ZaackGoat** [comment]
Now I have the same problem in the nether with pigman farms :(

**Comment by vlad2305m** [comment]
v2.0.0
