### ISSUE TITLE
1.17 barely working and Strange behavior

### ISSUE THREAD

**Issue by VoidPollo** [vlad2305m/fabric-per-player-spawns#6]
It doesn’t seem to be working properly in 1.17.

I tested this with a friend and an alt account, where I was at the end, my friend in his base and the alt account was sitting in an afk spot high in the sky for a gunpowder farm (2000+ blocks away from his base).

After nearly a whole hour I went from the end to the gunpowder farm to check how much it had produced, it only had 28 drops in one hour.

I waited a bit longer and nothing, so me and my friend logged off and I timed 5 minutes on the dot, when I logged to check in those 5 minutes it had produced 20 gunpowder, when we are online and far from the gunpowder farm it only produced 28 in 1 hour.

**Comment by iPollox** [comment]
I just took my friend into a superflat world, we were both 300 blocks away hovering at y150 (floor is y50), made it night time, and we observed that he consistently kept ~23/70 mobs while I had around ~45/70 mobs which is roughly the server mob cap.

Then I tested by going to positive 10K and he went to negative 10K at first I got ~64/70 while he got 34/70, I told him to move around a little and only then he also got ~60/70, which is kind of a weird behavior not to keep updating mobs unless he was moving between chunks.

Also, the render distance in the server is 24, and I believe he plays at 21 while I do 24, so thats 45.
The equation in the mod page says: (SRD•2+1)²•n_players/n_chunks_loaded_by_these_playres
By plugging the following: (24•2+1)²•2/45 = ~106 which we were 3x that amount at first and did not work until we just tested being much much further away, then again I'm not too sure if he ever moved between chunks in the first test.

**Comment by vlad2305m** [comment]
@iPollox I highly encourage you to get +debug version (from github tag) that allows you to see some numbers for your testing.

For example, you completely misinterpreted the formula. It should be mob_cap•(SRD•2+1)²•n_players²/n_chunks_loaded_by_these_playres (yes, i missed a square)
=> 70•(49)•4/4802 (you can check this number in creative) = 70•2 (And yes, I also messed up the formula a bit)
300 blocks away n_chunks ~= 3882, so 3882/4802•2•70 = 113

Also, going between chunks doesn't recalculate your coverage fully (see [line 136-](https://github.com/vlad2305m/fabric-per-player-spawns/blob/master/src/main/java/dev/lambdacraft/perplayerspawns/util/PlayerDistanceMap.java)) (only teleporting/relogging does, but mistakes never occur anyway)

Regarding the weird behaviour, I'd also like to know what's wrong with the code. Last time something similar occured ([#4](https://github.com/vlad2305m/fabric-per-player-spawns/issues/4)), I couldn't find it so I just rewrote the whole mod and it was gone. And I don't want to do that again.
Again, your flat testing does not show as low as 28 creepers per hour, like I wasn't able to recreate any of the weird bugs. (This mod does not affect the spawning in any other way than preventing it when number from creative reaches 70, so you can play around with that) And yes, I can't fix it yet.

**Comment by iPollox** [comment]
I'll try the +debug version and play around with alts and see what I sort of see.

**Comment by iPollox** [comment]
Yeah, something is off but I'm not sure what is.
I tried by myself with an alt on a lan-server and worked fine, and by that I mean just reading the +debug counter and seeing a few mobs on the surface while a gunpowder farm worked fine.

But, in the server (same mods, not lagging, etc) we got 3 players online and 1 alt, one of the players said there weren't any pillagers spawning in the outpost after a few minutes of moving around, then me and the other player logged off and nothing, the moment we disconnected the alt, the player reported that after just a few seconds the pillagers started spawning again.

**Comment by Phelms215** [comment]
Based on this issue I suspect the mod isn't ready for 1.17.1?

**Comment by vlad2305m** [comment]
There was a bug regarding players existing for too long in a row, can it be that one?

**Comment by vlad2305m** [comment]
???
