### ISSUE TITLE
Can't achieve mobcaps when a player floats high above another player

### ISSUE THREAD

**Issue by MeeniMc** [vlad2305m/fabric-per-player-spawns#7]
## At a glance

When two players share a 'spawn sphere', and one of the players if flying high in the sky (or any other way to position that player so that she would not cause any mobs to spawn if she were alone), the mobcap for the 'bottom' player is reduced, sometimes all the way to 0, depending on distance. 

## Setup

per-player-spawns 1.17-2.0.0
MC 1.17.1
carpet 1.4.44

## Replicate

1. get world: Gnembon 'flush mobfarms'
2. use carpet to spawn players at the following positions
  a. `player Steve spawn at -299 111 -149` and turn the two mobfarm towers on (levers on top of the two holes in the ground)
  b. `player Alex spawn at -313 148 -715` and turn the mobfarm tower on
3. position the real player with Alex on the spawn platform: mobcap is 140, (3 players, 2 sharing the same mobcap), ~120-135 or so mobs will spawn split in the two farms, both farms have a good rate
4. position the real player on top of Alex `tp -313 350 -715` (floating right above Alex): mobcap is still 140 (normal), mobcap use is ~135 (looks normal)
5. position the real player at -516 350 -782 (somewhat in Alex spawn area): mobcap increases to 197, of which about ~135 will be used (looks normal)
6. position the real player at -542 350 -640 (somewhat in Alex spawn area): mobcap increases to 200, **of which only 70 is used, HUHO**
7. `tp 1000 100 1000`, mobcab becomes 210, of which 190-210 is used (normal)

As you can see, player positioning in case 6. appears to cause some break in the logic. This position also happens to be "intermediate" between the two bots which may be the root cause of the bug.

**Comment by MeeniMc** [comment]
With the main feature of this mod integrated in the game, I stopped using it. Closing.

**Comment by vlad2305m** [comment]
Thanks for confirming
