### ISSUE TITLE
Mob Switch Not Working

### ISSUE THREAD

**Issue by Scorpio003** [vlad2305m/fabric-per-player-spawns#9]
Mobcap is supposed to be occupied by chunk loaded withers but is not treated like that or something along those lines. By removing the mod, the mob switch starts working and no hostile mobs spawn.

**Comment by vlad2305m** [comment]
Let me put it this way: this mod specifically fixes the mob switch bug. And having world mob limit just doesn't make any sense for this mod (as I can't "prioritize" players with less mobs or something).
